### ISSUE TITLE
rocketchat 

### ISSUE THREAD

**Issue by mremptypants** [saltyorg/Sandbox#339]
this fails to add the right commands for the roles.

rocket chat
internal/modules/cjs/loader.js:934

  throw err;
  ^
Error: Cannot find module '/app/bundle/b'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

command does this 
 a s h - c f o r i i n ` s e q 1 3 0 ` ; d o n o d e m a i n . j s & & s = $ $ ? & & b r e a k | | s = $ $ ? ; e c h o " T r i e d $ $ i t i m e s . W a i t i n g 5 s e c s . . . " ; s l e e p 5 ; d o n e ; ( e x i t $ $ s ) 

Rocketchat_db
/usr/local/bin/docker-entrypoint.sh: line 420: exec: m: not found

command does this. 
 	m o n g o d - - o p l o g S i z e 1 2 8 - - r e p l S e t r s 0

tried to fix it no luck

**Comment by mremptypants** [comment]
Ok,  so I got it all worked out, it will need some PR..I am new at them so I will do my best

it needs's [ ] around the commands in docker.

It needs this added 
mongodb://rocketchat_db:27017/local?replicaSet=rs0&directConnection=true
mongodb://rocketchat_db:27017/rocketchat?replicaSet=rs0&directConnection=true

the replica needs to change mongo to mongosh to work with 6.0.14

**Comment by owine** [comment]
Thanks, we would appreciate a PR with the fix up. Please join us on the Discord if you need assistance.

**Comment by saltydk** [comment]
I suspect this one will be a tad complicated @owine 
https://github.com/RocketChat/Docker.Official.Image/blob/master/compose.yml
